# Generated by Django 3.0.3 on 2020-09-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('countrycode', models.IntegerField(max_length=10)),
                ('tcases', models.IntegerField()),
                ('rcases', models.IntegerField()),
                ('dcases', models.IntegerField()),
            ],
        ),
    ]
