# Generated by Django 3.0.3 on 2020-09-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='countrycode',
            field=models.IntegerField(),
        ),
    ]
